echo "Start Enable DSA !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

echo "b 1 c 56000 dsa -----------------------------------------------------------------------------------"
ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 1 1 1 --input 56000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 57000 --cut-len 0

echo "b 2 c 48000 dsa -----------------------------------------------------------------------------------"
ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 2 2 2 --input 48000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 97000 --cut-len 0

echo "b 2 c 48000 dsa tbo -----------------------------------------------------------------------------------"
ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 2 2 2 --input 48000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 97000 --cut-len 0 --enable-two-batch-overlap --two-batch-overlap-mode heto --disable-cuda-graph-padding

echo "b 4 c 32000 dsa -----------------------------------------------------------------------------------"
ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 4 4 4 --input 32000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 129000 --cut-len 0

echo "b 4 c 32000 dsa tbo-----------------------------------------------------------------------------------"
ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 4 4 4 --input 32000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 129000 --cut-len 0 --enable-two-batch-overlap --two-batch-overlap-mode heto --disable-cuda-graph-padding

echo "Start DISABLE_DSA !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

echo "b 1 c 56000 -----------------------------------------------------------------------------------"
DISABLE_DSA=1 ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 1 1 1 --input 56000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 57000 --cut-len 0

echo "b 2 c 48000 -----------------------------------------------------------------------------------"
DISABLE_DSA=1 ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 2 2 2 --input 48000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 97000 --cut-len 0

echo "b 2 c 48000 tbo -----------------------------------------------------------------------------------"
DISABLE_DSA=1 ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 2 2 2 --input 48000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 97000 --cut-len 0 --enable-two-batch-overlap --two-batch-overlap-mode heto --disable-cuda-graph-padding

echo "b 4 c 32000 -----------------------------------------------------------------------------------"
DISABLE_DSA=1 ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 4 4 4 --input 32000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 129000 --cut-len 0

echo "b 4 c 32000 tbo-----------------------------------------------------------------------------------"
DISABLE_DSA=1 ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 4 4 4 --input 32000 --output 100 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 129000 --cut-len 0 --enable-two-batch-overlap --two-batch-overlap-mode heto --disable-cuda-graph-padding
