echo "mega=1 topk=1 dsa -----------------------------------------------------------------------------------"

STREAM_OUT=1 ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 DISABLE_DSA=0 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 1 --input 48000 --output 8000 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 80000 --cut-len 0 --correct  

echo "mega=0 topk=1 dsa -----------------------------------------------------------------------------------"

STREAM_OUT=1 ENABLE_MEGA_OPT=0 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 DISABLE_DSA=0 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 1 --input 48000 --output 8000 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 80000 --cut-len 0 --correct  

echo "mega=0 topk=0 dsa -----------------------------------------------------------------------------------"

STREAM_OUT=1 ENABLE_MEGA_OPT=0 ENABLE_ESIMD_TOPK_OPT=0 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 DISABLE_DSA=0 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 1 --input 48000 --output 8000 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 80000 --cut-len 0 --correct  

echo "mega=1 topk=1 disable dsa -----------------------------------------------------------------------------------"

STREAM_OUT=1 ENABLE_MEGA_OPT=1 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 DISABLE_DSA=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 1 --input 48000 --output 8000 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 80000 --cut-len 0 --correct  

echo "mega=0 topk=1 disable dsa -----------------------------------------------------------------------------------"

STREAM_OUT=1 ENABLE_MEGA_OPT=0 ENABLE_ESIMD_TOPK_OPT=1 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 DISABLE_DSA=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 1 --input 48000 --output 8000 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 80000 --cut-len 0 --correct  

echo "mega=0 topk=0 disable dsa -----------------------------------------------------------------------------------"

STREAM_OUT=1 ENABLE_MEGA_OPT=0 ENABLE_ESIMD_TOPK_OPT=0 ENABLE_ESIMD_NORM_ROPE_OPT=1 ENABLE_ESIMD_MLA_OPT=1 ENABLE_ESIMD_FP8_GEMM_OPT=1 DISABLE_DSA=1 ENABLE_NUMA=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/miniforge3/envs/ds_r2_d0_heto/lib:/root/miniforge3/envs/ds_r2_d0_heto/lib/python3.10/site-packages/xfastertransformer-devel/lib/ OMP_NUM_THREADS=22 CUDA_VISIBLE_DEVICES=1 XDNN_N64=64 ENABLE_MOE_ALIGN_BLOCK_SIZE_TRITON=1 TRITON_CACHE_DIR=/home/gta/triton_cache python -m sglang.bench_one_batch --batch-size 1 --input 48000 --output 8000 --model ~/model/DeepSeek-Math-V2/ --tp-size 4 --trust-remote-code --device xpu --attention-backend triton --dtype float16 --enable-ep-moe --enable-ep-moe-heto --ep-moe-heto-gpu-experts 0 --mem-fraction-static 0.8 --max-total-tokens 80000 --cut-len 0 --correct  
